/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/information/Badge.vue')['default']
    Button: typeof import('./src/components/controls/Button.vue')['default']
    Collapsible: typeof import('./src/components/containers/Collapsible.vue')['default']
    Drawer: typeof import('./src/components/containers/Drawer.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconCart: typeof import('./src/components/icons/IconCart.vue')['default']
    IconChevronDown: typeof import('./src/components/icons/IconChevronDown.vue')['default']
    IconCloseMark: typeof import('./src/components/icons/IconCloseMark.vue')['default']
    IconHamburger: typeof import('./src/components/icons/IconHamburger.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    Lists: typeof import('./src/components/data/Lists.vue')['default']
    ListWithBadge: typeof import('./src/components/information/ListWithBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextField: typeof import('./src/components/controls/TextField.vue')['default']
  }
}
